QUESTIONS = [
    {"Who initially recruits you into the Dark Brotherhood in Oblivion?": ["Lucien Lachance", "Arquen", "Ocheeva", "Vicente Valtieri"]},
    {"Who of the following is NOT a member of the Black Hand in Oblivion?": ["Alval Uvani", "Belisarius Arius", "Banus Alor", "Fafnir"]},
    {"Which cult did the Dark Brotherhood originally branch off from?": ["Morag Tong", "Commona Tong", "Mythic Dawn", "Thieves Guild"]},
    {"Teinaava and Ocheeva are both this, a special rank of assassins in Argonia. What is their special assassin rank?": ["Shadowscale", "Black Marsh Brother", "Royal Brotherhood Member", "Argonia Shadow"]},
    {"Vicente Valtieri offers you his Dark Gift after you complete which mission in Oblivion?": ["The Assassinated Man", "A Watery Grave", "Scheduled for Execution", "Accidents Happen"]},
    {"Where is Lucien Lachance's stronghold located in Oblivion?": ["Fort Farragut", "Fort Hastrel", "Fort Flecia", "Fort Ontus"]},
    {"In Oblivion, Vicente Valtieri complains about whose cooking as a hint that he is allergic to garlic?": ["Antoinetta Marie", "M'raaj-Dar", "Telaendril", "Gogron gro-Bolmog"]},
    {"According to rumors, Arquen did what to Lucien Lachance after he was killed in Oblivion?": ["Feasted on his entrails", "Saved a finger", "Claimed his head", "Left his body by the Night Mother's shrine"]},
    {"Who did the eighth Dead Drop quest ask you to assassinate before Lucien sends you after the traitor instead?": ["Arquen", "Banus Alor", "Shaleez", "Belisarius Arius"]},
    {"Where is the first Dark Brotherhood sanctuary you encounter in Skyrim?": ["Near Falkreath", "Near Solitude", "Near Windhelm", "Near Dawnstar"]},
    {"Where is the second Dark Brotherhood sanctuary in Skyrim?": ["Near Dawnstar", "Near Cheydinhal", "Near Markath", "Near Markarth"]},
    {"Which two characters survive the Oculatus agents' massacre of the sanctuary in Skyrim?": ["Nazir and Babette", "Astrid and Festus", "Nazir and Gabriela", "Astrid and Babette"]},
    {"Who is your first contact in Skyrim's Dark Brotherhood questline?": ["Muiri", "Amond Motiere", "Farkas", "Hulda"]},
    {"What is the name of the emperor you assassinate in Skyrim?": ["Titus Mede the Second", "Magnus Septim", "Uriel Septim", "Martin Septim"]},
    {"How did Cicero become a psychopathic jester?": ["It was a gift from the Night Mother", "He was born that way", "Sithis bestowed a power on him", "His father was one"]},
    {"Who or what is Sithis?": ["The Void", "A Daedric god", "Founder of the Dark Brotherhood", "The Night Mother's spouse"]},
    {"In which games do you encounter Shadowmere?": ["Oblivion and Skyrim", "Morrowind and Skyrim", "Morrowind and Oblivion", "Elder Scrolls Online and Skyrim"]},
    {"What is the Listener's role?": ["The person who listens to the Night Mother", "The person who listens to Sithis", "The person who listens to the Black Sacrament", "The person who listens to each member's personal problems"]},
    {"Which tenet is NOT part of the Five Tenets?": ["Never have any affiliation with Morag Tong", "Never dishonor the Night Mother", "Never kill a Dark Brother or Dark Sister", "Never betray the Dark Brotherhood or its secrets"]},
    {"Which beginning phrase starts the Black Sacrament?": ["Sweet Mother, sweet mother...", "Hear me Sithis...", "I beg thee Sithis...", "The void hungers..."]},
    {"Which step is NOT part of the Black Sacrament ritual?": ["An offer of gold", "Candles encircling", "Body parts representing the victim", "A dagger coated in nightshade"]},
    {"Why did Mathieu Bellamont want revenge on the Dark Brotherhood in Oblivion?": ["Lucien Lachance killed his mother", "His mother died defending him from the Brotherhood", "His mother was a Brotherhood member who died on a mission", "His mother was a worshipper of Mephala"]},
]
